@isTest
private class L2I_RateScheduleUtils_Test {
    @isTest static void myTest() {
        L2I_RateScheduleUtils c = new L2I_RateScheduleUtils();
        Test.startTest();
        L2I_RateScheduleUtils.placeHolderMethod();
        L2I_RateScheduleUtils.updateParentOnLoad('test');
        //L2I_LwcListController.TopRecordWrapper();
        //L2I_LwcListController.getColumnHeaderProperties('test,test,test,test,test,test,test,test,test,test,test,test,test');
        Test.stopTest();
    }
}