/**
 *      @author       Raj Rajen
 *      @date         07/10/2019
 *      @description  Enumerated types for Trigger execution modes
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Raj Rajen                     07/10/2019         Initial scaffold
 *
 */
public enum L2I_TriggerMode {
    INSERT_MODE,
    UPDATE_MODE,
    DELETE_MODE
}