@isTest
private class L2I_CustomListTablePropPickList_Test {
    @isTest static void myTest() {
        L2I_CustomListTablePropPickList c = new L2I_CustomListTablePropPickList();
        //ptc.L2I_PrecisionTailCountUtils(system.today(),true);
        //c.productUsageList();
        //L2I_Constants.BLANK_STRING='';
        //System.assertEquals(L2I_Constants.BLANK_STRING, '');
        Test.startTest();
        c.getDefaultValue();
        Test.stopTest();
    }
}