/**
 *      @author       Andy Fang
 *      @date         04/04/2020
 *      @description  L2I_CaseMgmtDAO
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Andy Fang                    04/04/2020         Initial scaffold
 *      Sarah Kennedy                06/10/2020         US1979 changed getOrderRecords to accept List<L2I_DSL__c> instead of List<Id>
 *      Sarah Kennedy                07/22/2020         Rel4 Sprint3 - no longer being used
 */


public interface L2I_CaseMgmtDAO {

//    List<Order> getOrderRecords( List<Id> quoteId, List<Id> dslIds  );
//    List<L2I_DSL__c> getDSLRecords( List<Id> quoteId, List<Id> dslIds );
//    List<Case> getExistingCaseByDSL( Set<Id> orderIdSets, Set<Id> acIdSets, Set<Id> dslIdSets );
//    List<OrderItem> getOrderItemByOrderId( Set<Id> OrderId );
//
//    Set<Id> CreateCases(List<L2I_DSL__c> dslList, List<Order> orderList, Set<String> uniqueCaseSet );
}